ALTER PROCEDURE BackOfficeUser_GetByUserId
	@UserId UNIQUEIDENTIFIER = ''
AS 
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT

	SELECT * 
	FROM BackOfficeUser WITH(NOLOCK)
 	WHERE UserId = @UserId 
END 
