CREATE PROCEDURE ArtistVerification_GetById
	@Id INT = 0
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;

	SELECT * 
	FROM ArtistVerification WITH(nolock)
	WHERE Id = @Id
	ORDER BY ModifiedDate DESC
END